name: Manual Approval Before Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          echo "Building the project..."
          mkdir -p dist
          echo "Build successful" > dist/index.html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production    # 🔒 Protected environment
      url: https://example.com    # optional URL shown in deployments tab
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          echo "Deployment complete ✅"
