name: Build and Upload Artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build || echo "No build script found, skipping build."

      - name: Create zip artifact
        run: |
          mkdir -p dist
          echo "Build output placeholder" > dist/index.html
          zip -r dist.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist.zip
