name: Dependency Caching with Restore Keys

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  cache-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
            ${{ runner.os }}-

      - name: Log cache hit status
        run: |
          if [ "${{ steps.cache-node-modules.outputs.cache-hit }}" == "true" ]; then
            echo "✅ Cache hit! node_modules restored from cache."
            echo "Cache key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}"
          else
            echo "❌ Cache miss! Dependencies will be installed."
            echo "Attempted key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}"
          fi

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Display cache information
        run: |
          echo "=== Cache Information ==="
          echo "Runner OS: ${{ runner.os }}"
          echo "Cache Key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}"
          echo "Cache Hit: ${{ steps.cache-node-modules.outputs.cache-hit }}"
          echo "Node modules directory size:"
          du -sh node_modules 2>/dev/null || echo "node_modules not found"

      - name: Run tests (optional)
        run: npm test --if-present